#!/usr/bin/env bash
# build_app.sh — Build OptionsTerminal.app via Platypus CLI
set -euo pipefail

PLATYPUS=/usr/local/bin/platypus
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ── 1. Check Platypus CLI ────────────────────────────────────────────────────
if [[ ! -x "$PLATYPUS" ]]; then
    echo "ERROR: Platypus CLI not found at $PLATYPUS"
    echo ""
    echo "Install steps:"
    echo "  1. brew install --cask platypus"
    echo "  2. Open Platypus.app → Preferences → Install Command Line Tool"
    echo "  3. Re-run this script."
    exit 1
fi

# ── 2. Detect Python interpreter ────────────────────────────────────────────
if [[ -f "$SCRIPT_DIR/venv/bin/python" ]]; then
    PYTHON="$SCRIPT_DIR/venv/bin/python"
elif [[ -f "$SCRIPT_DIR/.venv/bin/python" ]]; then
    PYTHON="$SCRIPT_DIR/.venv/bin/python"
else
    PYTHON="$(command -v python3 2>/dev/null || command -v python)"
fi
echo "Using Python: $PYTHON"

# ── 3. Write launcher.sh ─────────────────────────────────────────────────────
cat > "$SCRIPT_DIR/launcher.sh" <<LAUNCHER
#!/usr/bin/env bash
# launcher.sh — entry script for OptionsTerminal.app
# Auto-generated by build_app.sh — do not edit manually.

SCRIPT_DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"

# Activate virtualenv if present
if [[ -f "\$SCRIPT_DIR/venv/bin/activate" ]]; then
    source "\$SCRIPT_DIR/venv/bin/activate"
elif [[ -f "\$SCRIPT_DIR/.venv/bin/activate" ]]; then
    source "\$SCRIPT_DIR/.venv/bin/activate"
fi

export TERM=xterm-256color
cd "\$SCRIPT_DIR"
exec "$PYTHON" "\$SCRIPT_DIR/tui.py" --session-name "OPTIONS TERMINAL"
LAUNCHER
chmod +x "$SCRIPT_DIR/launcher.sh"
echo "Wrote: $SCRIPT_DIR/launcher.sh"

# ── 4. Remove existing .app bundle ──────────────────────────────────────────
if [[ -d "$SCRIPT_DIR/OptionsTerminal.app" ]]; then
    rm -rf "$SCRIPT_DIR/OptionsTerminal.app"
    echo "Removed existing OptionsTerminal.app"
fi

# ── 5. Build with Platypus ───────────────────────────────────────────────────
"$PLATYPUS" \
    --name                "OptionsTerminal" \
    --interface-type      "Text Window" \
    --interpreter         "/bin/bash" \
    --author              "OptionDashboard" \
    --bundle-identifier   "com.optiondashboard.terminal" \
    --app-version         "1.0" \
    --overwrite \
    "$SCRIPT_DIR/launcher.sh" \
    "$SCRIPT_DIR/OptionsTerminal.app"

echo ""
echo "✓  Built: $SCRIPT_DIR/OptionsTerminal.app"
echo ""
echo "Next steps:"
echo "  • Double-click OptionsTerminal.terminal once to install the Terminal profile."
echo "  • Then double-click OptionsTerminal.app to launch the TUI."
echo "  • Or use launch.sh for a direct Terminal.app window: bash launch.sh"
